name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Current directory: $(pwd): $GITHUB_WORKSPACE"
          git clone https://github.com/akifejaz/15_puzzle test_dir
          ls *

          mkdir $GITHUB_WORKSPACE/rpm_pkg
          cd $GITHUB_WORKSPACE/rpm_pkg
          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp $GITHUB_WORKSPACE/test_dir/15_puzzle.spec rpmbuild/SPECS/15_puzzle.spec
          cp -rf $GITHUB_WORKSPACE/test_dir rpmbuild/SOURCES/15_puzzle-1.0          
          tar --create --file rpmbuild/SOURCES/15_puzzle-1.0.tar.gz rpmbuild/SOURCES/15_puzzle-1.0
          ls $GITHUB_WORKSPACE/rpm_pkg/rpmbuild
          rpmbuild -ba rpmbuild/SPECS/15_puzzle.spec
          
      - name: Print
        run: |
           ls ~/rpmbuild/*
           
      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: 15_puzzle
          path: $GITHUB_WORKSPACE/rpm_pkg/rpmbuild/RPMS
