name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.17.0'

    - name: Build
      run: |
        make clean
        make

    - name: Make RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        # move one step back 
        cd ..; ls -l
        cp -r 15_puzzle ~/rpmbuild/SOURCES/15_puzzle-1.0
        tar --create --file ~/rpmbuild/SOURCES/15_puzzle-1.0.tar.gz ~/rpmbuild/SOURCES/15_puzzle-1.0
        cp 15_puzzle/15_puzzle.spec ~/rpmbuild/SPECS/15_puzzle.spec
        rpmbuild -ba --define "_topdir ~/rpmbuild" rpmbuild/SPECS/pakage.spec

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: 15_puzzle
        path: ~/rpmbuild/RPMS/x86_64/15_puzzle-1.0-1.x86_64.rpm
