name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Current directory: $(pwd)"
          git clone https://github.com/akifejaz/15_puzzle
          cd 15_puzzle
          make clean
          make

          echo "Current directory: $(pwd)"
          ls 
          find . -name 15_puzzle.spec -exec readlink -f {} \;
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          mv ../15_puzzle ~/rpmbuild/SOURCES/15_puzzle-1.0
          tar --create --file ~/rpmbuild/SOURCES/15_puzzle-1.0.tar.gz ~/rpmbuild/SOURCES/15_puzzle-1.0
          # cp /home/runner/work/15_puzzle/15_puzzle/15_puzzle/15_puzzle.spec ~/rpmbuild/SPECS/15_puzzle.spec
          # rpmbuild -ba --define "_topdir ~/rpmbuild" ~/rpmbuild/SPECS/15_puzzle.spec

      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: 15_puzzle
          path: ~/rpmbuild/RPMS/x86_64/15_puzzle-1.0-1.x86_64.rpm
